### ISSUE TITLE
Docker ./waf configure fail when followning ardupilot wiki 

### ISSUE THREAD

**Issue by maripuusiim** [flaperon-co/ardupilot#1]
## Bug report

Docker builds and conteiner runs, but error when trying to build ardupilot code when following:
[setup build env](https://ardupilot.org/dev/docs/building-setup-linux.html#id1)
&
[build code](https://ardupilot.org/dev/docs/building-for-bebop-2.html)

Steps:
git clone --recurse-submodules https://github.com/your-github-userid/ardupilot
cd ardupilot
docker build . -t ardupilot
docker run --rm -it -v `pwd`:/ardupilot ardupilot:latest bash
./waf configure --board=Pixhawk4
./waf build

Same issue:
[original repo issue](https://github.com/ArduPilot/ardupilot/issues/25779)

Similar issue discussion on discord:
[Ardupilot Discord](https://discord.com/channels/674039678562861068/1078155643246092308)

**Version**
master, Copter-4.5

**Platform**
[  ] All
[  ] AntennaTracker
[*] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Pixhawk4, Pixhawk6X

**Logs**

**Comment by kuido85** [comment]
Execute container with ardupilot user e.g. `docker run --rm -it -u ardupilot -v $PWD:/ardupilot ardupilot:latest bash
`


btw, it doesn't work in docker-desktop, use docker engine.

**Comment by maripuusiim** [comment]
Confirmed, docker-desktop was the issue. 

Works with these steps on ubuntu 22.04 lts:

# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Follow these:
https://github.com/sindresorhus/guides/blob/main/docker-without-sudo.md

# Clone ardupilot & build
git clone --recurse-submodules https://github.com/flaperon-co/ardupilot.git
cd ardupilot
docker build . -t ardupilot
docker run --rm -it -v `pwd`:/ardupilot ardupilot:latest bash
./waf configure
./waf build
